dependencies:
- name: traefik
  version: "1.77.1"
  repository: https://kubernetes-charts.storage.googleapis.com
  condition: traefik.enabled
- name: aws-alb-ingress-controller
  version: "1.0.2"
  repository: https://kubernetes-charts-incubator.storage.googleapis.com/
  condition: aws-alb-ingress-controller.enabled
- name: elasticsearch
  version: "7.8.1"
  repository: https://helm.elastic.co/
  condition: elasticsearch.enabled
- name: fluentd-elasticsearch
  version: "9.6.0"
  repository: https://kiwigrid.github.io/
  condition: fluentd-elasticsearch.enabled
- name: kibana
  version: "7.8.1"
  repository: https://helm.elastic.co/
  condition: kibana.enabled
- name: metrics-server
  version: "2.8.4"
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: metrics-server.enabled
- name: ingress-azure
  version: "1.2.0"
  repository: https://appgwingress.blob.core.windows.net/ingress-azure-helm-package/
  condition: ingress-azure.enabled
